### PR TITLE
get things working again

### PR DESCRIPTION
**Pull request by ffreyer**
Compiles and runs again, but doesn't look right in GLMakie
Screenshot from 2021-03-05 14-38-57

### CODE REVIEW

**Comment by ffreyer** [comment]
Changes:
* fix requirements, syntax (first commit)
* changed `dpi` to 72 across the board. This seems to be what CairoMakie uses
* adjusted `teximg` to draw at 1:1 resolution in GLMakie
* removed position/bbox argument for a `postion` attribute
* added `textsize` which acts as a multiplier to the tex output. `textsize` and `dpi` can be used to scale the image
* changed `LTeX` to be more like `Label`

**Comment by ffreyer** [comment]
Output from
```julia
fig = Figure(resolution = (500, 500));
ax = Axis(fig[1, 1]);
hidexdecorations!(ax); hideydecorations!(ax);
tex = MakieTeX.LTeX(fig[2, 1], raw"\int \mathbf E \cdot d\mathbf a = \frac{Q_{encl}}{4\pi\epsilon_0}", textsize=20);
fig
```
in a VSCode pane vs GLMakie. 
Screenshot from 2021-03-06 18-42-05

**Comment by ffreyer** [comment]
Added `rotation` via the model matrix but I think that is ignored when generating bounding boxes so the layouting doesn't quite work right.

**Comment by SimonDanisch** [comment]
Awesome to have this working again :) Should we just merge & tag this?

**Comment by ffreyer** [comment]
Yes :)

**Pull request merged**
